"""Fit synthetic generator parameters from raw-IQ feature estimates (V1).

Reads outputs/real_samples/feature_params_iq.csv (from extract_raw_features.py)
and writes configs/fitted_params.yaml, which the exporter loads with highest
priority (fitted > real-informed overrides > paper Table 4).

Usage: python scripts/fit_drone_params.py --drone DJI_MINI3
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from gaema_rfuav_synth.rfuav.iq_feature_extractor import extract_iq_features
from gaema_rfuav_synth.signal.fhss_generator import FHSSParams, generate_fhss
from gaema_rfuav_synth.signal.snr import add_awgn_at_snr


def calibrate_burst_bw(
    target_measured_mhz: float,
    fhsdt_ms: float,
    fhsdc_ms: float,
    hop_span_mhz: float,
    fs: float = 100e6,
) -> float:
    """Closed-loop bandwidth calibration.

    The feature extractor over-measures narrow bursts by ~2 STFT bins
    (window mainlobe smearing), on real and synthetic alike. We therefore fit
    the generator's CONFIGURED bandwidth so that the MEASURED bandwidth of a
    generated signal matches the measured real value.
    """
    bw = max(target_measured_mhz * 0.6, 0.2)
    for _ in range(5):
        p = FHSSParams(
            fhsbw_mhz=bw, fhsdt_ms=fhsdt_ms, fhsdc_ms=fhsdc_ms,
            fhspp_ms=fhsdc_ms * 8, hop_span_mhz=hop_span_mhz,
        )
        sig, _ = generate_fhss(p, fs, 0.05, np.random.default_rng(0))
        noisy, _ = add_awgn_at_snr(sig, 15.0, np.random.default_rng(1))
        m = extract_iq_features(noisy, fs)["estimated_bandwidth_mhz"]
        if m is None:
            break
        err = m - target_measured_mhz
        if abs(err) / target_measured_mhz < 0.05:
            break
        bw = max(bw - err * 0.8, 0.1)
    return bw


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--drone", required=True)
    ap.add_argument("--features", default="outputs/real_samples/feature_params_iq.csv")
    ap.add_argument("--out", default="configs/fitted_params.yaml")
    args = ap.parse_args()

    df = pd.read_csv(args.features)
    df = df[df["drone"] == args.drone]
    if df.empty:
        raise SystemExit(f"no raw-IQ features for {args.drone}; run extract_raw_features.py first")

    fhsdc = float(df["estimated_hopping_interval_ms"].median())
    bw_measured = float(df["estimated_bandwidth_mhz"].median())
    fhsdt = float(df["estimated_burst_duration_ms"].median())
    span = float(df["estimated_hop_span_mhz"].median())
    bw_cal = calibrate_burst_bw(bw_measured, fhsdt, fhsdc, span)
    fitted = {
        "burst_bw_mhz": round(bw_cal, 3),
        "burst_bw_measured_mhz": round(bw_measured, 3),
        "fhsdt_ms": round(float(df["estimated_burst_duration_ms"].median()), 4),
        "fhsdc_ms": round(fhsdc, 4),
        "hop_span_mhz": round(float(df["estimated_hop_span_mhz"].median()), 2),
        # irregularity from observed std, capped at physical limits (raw stds
        # are inflated by merged regions and missed detections)
        "timing_jitter_ms": round(
            min(float(df["estimated_hopping_interval_std_ms"].median() or 0.1) / 2, fhsdc / 4), 4
        ),
        "duration_jitter_frac": round(
            min(
                float(
                    (df["estimated_burst_duration_std_ms"].median() or 0.0)
                    / max(float(df["estimated_burst_duration_ms"].median()), 1e-6)
                ),
                0.3,
            ),
            3,
        ),
        "amp_jitter_db": 1.5,
        "freq_jitter_mhz": round(float(df["estimated_bandwidth_mhz"].median()) * 0.1, 3),
        "snr_db_observed": round(float(df["estimated_snr_db"].median()), 2),
        "fitted_from": str(df["source_file"].iloc[0]),
    }

    out = Path(args.out)
    existing = yaml.safe_load(out.read_text()) if out.exists() else {}
    existing = existing or {}
    existing[args.drone] = fitted
    header = (
        "# Generated by scripts/fit_drone_params.py from real raw-IQ estimates.\n"
        "# Loaded by the exporter with priority: fitted > overrides > paper.\n"
    )
    out.write_text(header + yaml.safe_dump(existing, sort_keys=False))
    print(f"[done] {args.drone} -> {out}")
    print(yaml.safe_dump({args.drone: fitted}, sort_keys=False))


if __name__ == "__main__":
    main()
